### ISSUE TITLE
Using a directory rather than a repository with --localclone does not exit or throw a sane error

### ISSUE THREAD

**Issue by jcayouette** [uyuni-project/uyuni-docs-helper#17]
Running the helper with the `-l` or `--localclone` option produces an unclear output when used with local directory rather than a repository. The help shows you should use a repo, but the script should cancel and throw an error if a `.git` directory is not detected.

For example:
`./uyuni-docs-helper -l ./tmp -r fixCobblerDistroLabelInstructions  -c antora-suma-en -p suma`

```
====================================================================
 Git repository: A folder from outside the container is being used
 Product: suma
 Make command: antora-suma-en
====================================================================
make: *** No rule to make target 'configure-suma'.  Stop.
make: *** No rule to make target 'antora-suma-en'.  Stop.
[INFO] You can find find the build output at ./tmp/build
[ERROR] There were errors! Please review the log!
```

**Comment by juliogonzalez** [comment]
For reference: As discussed, the fix is checking if the directory provided with `-l` is a git repo or not, and if not then exiting without even starting the container. 

I will see what I can do.

**Comment by juliogonzalez** [comment]
And as a bonus: 
```
[INFO] You can find find the build output at ./tmp/build
[ERROR] There were errors! Please review the log!
```
This need to be reworked a bit as well. Even with errors there can be outputs, but we should improve the messages a little.
